apiVersion: batch/v1
kind: Job
metadata:
  name: topic-create-event-kube
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: topic-create
        image: solsson/kafka:native-cli@sha256:7a4cc4ef875aea50b8d4dbb525cbac0ef3a5c6e611fcafc2c415ca432ebe5601
        command:
        - ./bin/kafka-topics.sh
        - --zookeeper
        -   zookeeper.kafka.svc.cluster.local:2181
        - --create
        - --if-not-exists
        - --topic
        -   ops.kube-events.stream.json
        resources:
          limits:
            cpu: 100m
            memory: 20Mi
      restartPolicy: Never
