apiVersion: v1
kind: Service
metadata:
  name: redpanda
  labels:
    app: redpanda
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - port: 9092
    name: kafka
  selector:
    app: redpanda
