apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  selector:
    matchLabels:
      app: redpanda
  serviceName: "redpanda" # See also the POD_IPS_DNS env
  replicas: 3             # See also the REPLICAS env
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redpanda
        image: vectorized/redpanda:release-20.11.6@sha256:8ec2c8c15d14861c1ceda142cb939d2e916789a0cee88d95e27eef2c7753efa3
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ROOT_DNS
          value: redpanda-root
        - name: REPLICAS
          value: "3"
        ports:
        - name: kafka
          containerPort: 9092
        - name: rpc
          containerPort: 33145
        - name: admin
          containerPort: 9644
        command:
        - /bin/bash
        - -ceuxo
        - pipefail
        - --
        args:
        - |
          id
          echo "Pod IP: $POD_IP"
          rpk check
          NODE_ID=${HOSTNAME##*-}
          mkdir /tmp/redpanda
          if [ "$NODE_ID" -eq 0 ]; then
            rpk config bootstrap --id $NODE_ID --config /tmp/redpanda/redpanda.yaml --self $POD_IP
            rpk config init --config /tmp/redpanda/redpanda.yaml
          else
            getent hosts $ROOT_DNS | tee /tmp/hosts-$ROOT_DNS
            ROOT_IPS=$(cat /tmp/hosts-$ROOT_DNS | awk '{ print $1 }' | paste -sd "," - )
            rpk config bootstrap --id $NODE_ID --config /tmp/redpanda/redpanda.yaml --ips $ROOT_IPS --self $POD_IP
          fi
          cat /tmp/redpanda/redpanda.yaml
          rpk start --config /tmp/redpanda/redpanda.yaml
